import type { Metadata, Viewport } from "next";
import { Outfit } from "next/font/google";
import Script from "next/script";
import { getGoogleReviews } from "./lib/google-reviews";
import {
  JUST_EAT_RATING,
  JUST_EAT_COUNT,
  GOOGLE_FALLBACK_RATING,
  GOOGLE_FALLBACK_COUNT,
} from "./lib/review-stats";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-display",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});

const SITE_URL = "https://www.wokandflame.co";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Wok & Flame | Chinese Takeaway in West Didsbury, Manchester",
    template: "%s | Wok & Flame",
  },
  description:
    "Authentic Chinese takeaway, wok-fired in West Didsbury, Manchester. Salt & pepper, crispy duck, chow mein and a handful of Thai favourites. Delivery and collection — order online or call 0161 434 6318.",
  applicationName: "Wok & Flame",
  keywords: [
    "Chinese takeaway West Didsbury",
    "Chinese takeaway M20",
    "Chinese takeaway Manchester",
    "Chinese delivery Didsbury",
    "salt and pepper chicken Didsbury",
    "crispy duck Manchester",
    "Thai takeaway West Didsbury",
    "Burton Road takeaway",
    "Wok and Flame Manchester",
    "Chinese food near me Didsbury",
  ],
  authors: [{ name: "Wok & Flame", url: SITE_URL }],
  creator: "Wok & Flame",
  publisher: "Wok & Flame",
  alternates: {
    canonical: SITE_URL,
    languages: { "en-GB": SITE_URL },
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_GB",
    url: SITE_URL,
    siteName: "Wok & Flame",
    title: "Wok & Flame | Chinese Takeaway in West Didsbury, Manchester",
    description:
      "Wok-fired Chinese & Thai takeaway in West Didsbury. Salt & pepper, crispy duck, chow mein. Delivery & collection.",
    images: [
      {
        url: "/images/full-spread.webp",
        width: 1200,
        height: 630,
        alt: "Wok & Flame — Chinese takeaway, West Didsbury",
        type: "image/webp",
      },
    ],
  },
  manifest: "/manifest.webmanifest", // generated by app/manifest.ts (TODO)
  category: "restaurant",
  classification: "Chinese takeaway",
  formatDetection: {
    telephone: true, // keep tap-to-call detection on for 0161 434 6318
    email: true,
    address: true,
  },
  appleWebApp: {
    capable: true,
    title: "Wok & Flame",
    statusBarStyle: "black-translucent",
  },
  // Search-engine verification — paste codes from Search Console / Bing once
  // verified. DNS-TXT verification is the alternative and doesn't need these.
  verification: {
    google: "", // from Search Console HTML-tag method
    yandex: "",
    other: {
      "msvalidate.01": "", // Bing Webmaster Tools meta tag
    },
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0c0a09" },
    { media: "(prefers-color-scheme: light)", color: "#0c0a09" },
  ],
  colorScheme: "dark",
};

// LocalBusiness / Restaurant JSON-LD — drives Google rich results for hours,
// rating, address, and the AI Overviews citation surface (ChatGPT search,
// Perplexity, Google AI Overviews all read this).
//
// All review-stat constants now live in app/lib/review-stats.ts so the
// schema's aggregateRating stays in lockstep with the visual surfaces.
function buildRestaurantSchema(googleRating: number, googleCount: number) {
  const totalCount = JUST_EAT_COUNT + googleCount;
  const weightedRating = totalCount > 0
    ? ((JUST_EAT_RATING * JUST_EAT_COUNT) + (googleRating * googleCount)) / totalCount
    : JUST_EAT_RATING;

  return {
    "@context": "https://schema.org",
    "@type": "Restaurant",
    "@id": `${SITE_URL}/#restaurant`,
    name: "Wok & Flame",
    url: SITE_URL,
    telephone: "+44-161-434-6318",
    image: `${SITE_URL}/images/full-spread.webp`,
    servesCuisine: ["Chinese", "Thai"],
    priceRange: "££",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Burton Road",
      addressLocality: "West Didsbury",
      addressRegion: "Manchester",
      postalCode: "M20 2LW",
      addressCountry: "GB",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: 53.4266560,
      longitude: -2.2429775,
    },
    hasMap: "https://www.google.com/maps/search/?api=1&query=53.4266560,-2.2429775",
    acceptsReservations: false,
    aggregateRating: {
      "@type": "AggregateRating",
      ratingValue: weightedRating.toFixed(2),
      reviewCount: totalCount,
      bestRating: "5",
      worstRating: "1",
    },
    openingHoursSpecification: [
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Sunday"],
        opens: "16:55",
        closes: "22:00",
      },
      {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Friday", "Saturday"],
        opens: "16:55",
        closes: "23:00",
      },
    ],
    menu: `${SITE_URL}/#menu`,
    potentialAction: {
      "@type": "OrderAction",
      target: "https://www.just-eat.co.uk/restaurants-wokandgo-m20/menu",
      deliveryMethod: ["http://purl.org/goodrelations/v1#DeliveryModeOwnFleet"],
    },
    areaServed: [
      { "@type": "Place", name: "West Didsbury" },
      { "@type": "Place", name: "Didsbury" },
      { "@type": "Place", name: "Withington" },
      { "@type": "Place", name: "Chorlton" },
      { "@type": "Place", name: "Manchester M20" },
      { "@type": "Place", name: "Manchester M21" },
    ],
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Pull live Google rating + count from Places API when configured. Falls
  // back to the documented placeholder so the schema is always populated.
  const googleData = await getGoogleReviews();
  const googleRating = googleData?.rating ?? GOOGLE_FALLBACK_RATING;
  const googleCount = googleData?.reviewCount ?? GOOGLE_FALLBACK_COUNT;
  const restaurantSchema = buildRestaurantSchema(googleRating, googleCount);

  // WebSite schema — enables Google's sitelinks search box and gives every
  // AI search engine a clear entity to bind to.
  const websiteSchema = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    url: SITE_URL,
    name: "Wok & Flame",
    description: "Chinese takeaway in West Didsbury, Manchester",
    inLanguage: "en-GB",
    publisher: { "@id": `${SITE_URL}/#restaurant` },
  };

  return (
    <html lang="en" className={outfit.variable}>
      <head>
        {/* Leaflet CSS — required for the open-source OpenStreetMap component
            in components/LocationMap.tsx. Pinned to a known version. */}
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossOrigin=""
        />
        <link rel="preconnect" href="https://tile.openstreetmap.org" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(restaurantSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
      </head>
      <body className="font-display min-h-[100dvh]">
        {children}
        {/* Leaflet JS — afterInteractive keeps it out of the critical path */}
        <Script
          src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
          crossOrigin=""
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
