import type { MetadataRoute } from "next";

// PWA manifest — generated by Next.js at /manifest.webmanifest.
// Lets browsers install the site as an app and gives Google a clear app-name
// signal in search results. Once /public/icon-192.png and /public/icon-512.png
// exist, the install prompt actually fires on Chrome / Edge.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Wok & Flame — Chinese Takeaway, West Didsbury",
    short_name: "Wok & Flame",
    description:
      "Authentic Chinese takeaway, wok-fired fresh in West Didsbury, Manchester. Delivery and collection.",
    start_url: "/",
    display: "standalone",
    background_color: "#0c0a09",
    theme_color: "#0c0a09",
    orientation: "portrait",
    categories: ["food", "restaurants"],
    lang: "en-GB",
    icons: [
      {
        src: "/icon-192.png", // TODO: drop into /public
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png", // TODO: drop into /public
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512-maskable.png", // TODO: drop into /public
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
